### ISSUE TITLE
Missing translation of schematron error rule|text|BR-OPT-00310-0100

### ISSUE THREAD

**Issue by rkottmann** [OP-TED/eForms-SDK#165]
We have a Schematron error with code `rule|text|BR-OPT-00310-0100` (efac:TenderingParty/cbc:ID) but can not find it in any translation file.

Is it missing?

**Comment by bertrand-lorentz** [comment]
From what I can see the text is present in rule_en.xml, at least since SDK version 1.0.0 :

`<entry key="rule|text|BR-OPT-00310-0100">Every reference to a TenderingParty from a LotTender (OPT-310-Tender) must match one of the defined Tendering Parties (OPT-210-Tenderer)</entry>`

It has not been translated yet, so it is not available in any other language.

**Comment by rkottmann** [comment]
Sry, I got this from someone else and thought I verified this with the following searches: https://github.com/OP-TED/eForms-SDK/search?q=BR-OPT-00310-0100 and https://github.com/OP-TED/eForms-SDK/search?q=rule|text|BR-OPT-00310-0100

The translation file does not appear then 😮 Will search local next time.
