### ISSUE TITLE
Circular reference problem with OPT-300-Procedure-SProvider

### ISSUE THREAD

**Issue by arinurkkala** [OP-TED/eForms-SDK#207]
We intend to use object constructors and this field turns it into a circular reference. Could something be done about this particular field?

"id" : "OPT-300-Procedure-SProvider",
"parentNodeId" : "ND-ProviderParty",
"name" : "Service Provider Technical Identifier Reference",
"btId" : "OPT-300",
"xpathAbsolute" : "/*/cac:ContractingParty/cac:**Party**/cac:**ServiceProviderParty**/cac:**Party**/cac:PartyIdentification/cbc:ID",

**Comment by arinurkkala** [comment]
Also from the XSD schema, PartyType has AgentParty that is of type PartyType.. this also creates a circular reference.

**Comment by bertrand-lorentz** [comment]
Hello,
The fact that the element `cac:Party` can have as it descendant another `cac:Party` element is a design choice in the UBL standard, so it's not something we can change. This does indeed make it possible to get into circular references or infinite recursion if you're only looking at the XSD.

In order to avoid this, I would suggest to use the structure of fields and nodes defined in fields.json.
For you example with the field "OPT-300-Procedure-SProvider", its "xpathRelative" property is `cac:PartyIdentification/cbc:ID`, and its parent is the node "ND-ProviderParty". This node then has its own relative XPath, and a parent node:
 ```
   "id" : "ND-ProviderParty",
    "parentId" : "ND-ServiceProviderParty",
    "xpathAbsolute" : "/*/cac:ContractingParty/cac:Party/cac:ServiceProviderParty/cac:Party",
    "xpathRelative" : "cac:Party",
    "repeatable" : false
```

So by following this tree structure you should be able to build a representation of the structure of an XML eForms notice, without any circular references.
See this page for information on how the XML structure is represented: https://docs.ted.europa.eu/eforms/1.3.2/fields/xml-structure.html

I hope this helps.

As this is not an issue in the SDK, I'm closing this. Feel free to provide feedback or share your experience in the "Discussions" forum.
