### ISSUE TITLE
Some 'test' attributes are inconsistent between schematron asserts and example reports failed-asserts

### ISSUE THREAD

**Issue by openegi** [OP-TED/eForms-SDK#251]
## Description

In the schematrons, asserts
* BR-BT-00004-0052,
* BR-BT-00701-0052,
* BR-BT-01252-0052

check that the content of the node matches the regular expression `^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$`

In example SVRL reports, the regex included in the failed asserts is `^[a-f0-9]8-[a-f0-9]4-4[a-f0-9]3-[89ab][a-f0-9]3-[a-f0-9]12$`. The regex no longer includes the curly braces.

### Example

In `static/validation-stage-3b.sch`:

```xml
<rule context="/*/cbc:ID[@schemeName='notice-id']">
        <assert id="BR-BT-00701-0052" role="ERROR" test="matches(normalize-space(.),'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$')">rule|text|BR-BT-00701-0052</assert>
</rule>
```

In `example/reports/INVALID_can_24_stage-2.svrl`:

```xml
<svrl:fired-rule context="/*/cbc:ID[@schemeName='notice-id']"/>
<svrl:failed-assert id="BR-BT-00701-0052"
                   location="/ContractAwardNotice/cbc:ID"
                   role="ERROR"
                   test="matches(normalize-space(.),'^[a-f0-9]8-[a-f0-9]4-4[a-f0-9]3-[89ab][a-f0-9]3-[a-f0-9]12$')">
    <svrl:text>rule|text|BR-BT-00701-0052</svrl:text>
</svrl:failed-assert>
```

**Comment by bertrand-lorentz** [comment]
Thanks for your feedback.
This is indeed an issue in the tool we use to generate those reports: when creating the validation report, the curly braces are incorrectly interpreted as "attribute value templates", which allow the evaluation of an expression surrounded by curly braces. So `{8}` evaluates to `8`.
We'll try to get this fixed so that the reports in the next version of the SDK are correct.

For information, this issue does not affect the validation reports returned by our "Central Validation Service", as it uses another Schematron implementation.

**Comment by bertrand-lorentz** [comment]
This has been corrected in the "develop" branch, and will be included in the next release of the SDK.
So I'm closing this issue.
