### ISSUE TITLE
Missing validation text messages for some BT-198-fields

### ISSUE THREAD

**Issue by gabrieledall** [OP-TED/eForms-SDK#295]
Comparing text messages for BT-198(xxx)-Fields in fields.json as well as in rule_en.xml-file, I realized that some error-messages named in fields.json are missing in rules_en.xml.

Is seems as if the missing messages belong to rules that have been added somehow later in the definition-process. Some of the missing rules are:
rule|text|BR-BT-00198-4292
rule|text|BR-BT-00198-4293

rule|text|BR-BT-00198-4335
rule|text|BR-BT-00198-4357

Since rules from rule|text|BR-BT-00198-1301 to rule|text|BR-BT-00198-1350 contain the same text-message as rule|text|BR-BT-00198-4292, rule|text|BR-BT-00198-4335 and rules from rule|text|BR-BT-00198-4052 to rule|text|BR-BT-00198-4101 have the same text message as rule|text|BR-BT-00198-4293, rule|text|BR-BT-00198-4357: wouldn't it be easier to define these messages only once and refer to the same message code whereever/whenever it is needed?

**Comment by bertrand-lorentz** [comment]
Thanks for your feedback.
From what I can see, the 4 messages you refer to are currently present in rule_en.xml, and they were already present in recent versions of the SDK. Which version of the SDK are you using ?

Some of the messages for rule are indeed currently identical, in particular for the BT-198(xxx) fields.
We have chosen to systematically have one message for each rule, so that the message identifier can be built directly from the identifier of the rule. This also allows us to easily modify the message for one rule, without impacting others or having to create a new message.

**Comment by gabrieledall** [comment]
Thank you for your clarification and I have to apologize for this issue, which was my fault: I thought I was using rules_en from sdk 1.5.0 but in fact I was using 1.1.0 - the rules had not been in there.
Once again sorry.

**Comment by bertrand-lorentz** [comment]
No problem, happy that the problme was resolved.
So I'm closing this issue.
