### ISSUE TITLE
Questions regarding BT-06 Strategic Procurement

### ISSUE THREAD

**Issue by UHMYND** [OP-TED/eForms-SDK#302]
Looking at the documentation here: 

https://docs.ted.europa.eu/eforms/latest/schema/procedure-lot-part-information.html#strategicProcurementSection 

it shows that the BT-06 is repeated once for each type of strategic procurement objective.
 
However, this example file: 

https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/cn_24_maximal.xml

have individual Lots with environmental-impact, social-impact and innovative-acquisition but only one BT-06 (env-imp).
 
Question 1: Is it correctly understood that BT-06 should be provided once for each type of strategic objective in the notice (like the documentation) and that the sample file is incorrect? 
 
Question 2: The BT-06 codelist has a value "none" as an option, however BT-06 is not mandatory. Is the omission of BT-06 semantically equivalent to providing BT-06 with value 'none'?

**Comment by YvesJo** [comment]
Hi,
I will try to  rephrase your question in order to make sure I properly catch it.
You wouldn't expect the existence of BT-774, BT-775 or BT-776 without the existence of the respectively corresponding BT-06 (env-imp, soc-obj and inn-pur).
So far no such rule has been defined. Also all the fields BT-06, BT-777, BT-774, BT-775 and BT-776 have been left optional with tailoring option left at national level (cf. [discussion on github](https://github.com/eForms/eForms/issues/314#issuecomment-495568169)); also with that we can not exclude the use of BT-774, BT-775 and BT-776 without the one of BT-06. 
For each of the project dimensions (innovation, social, and innovation) of the project/product/service shall there always be a BT-06 (i.e. a technical specification, selection criterion, award criterion, or contract performance condition)? certainly, this has however to be clarified by the business.
Regarding the "none" value, for a given Lot, it should not coexist with any of the following: env-imp, soc-obj or inn-pur. Not specifying BT-06 is semantically different than specifying BT-06 with the value none, the last case being unambiguous. When specifying BT-06 at edition,, the same logic should apply for all possible values, i.e. when specified, then all applicable values should be specified (BT-06 along with its description BT-777). If rules should be implemented and depending on the rules, situations like the one of the example you referred to could lead to a validation error and require an update.
This issue is purely non-technical, so I will close this issue and invite you to contact the helpdesk instead: [ted@publications.europa.eu](mailto:ted@publications.europa.eu)
Thanks for your understanding,
