### ISSUE TITLE
URL-Validation patterns too restrictive

### ISSUE THREAD

**Issue by gabrieledall** [OP-TED/eForms-SDK#479]
In Schematron as well as in fields.json currently all URL/URI Fields are checked against the same pattern which is like this:

},
    "pattern" : {
      "value" : "^((((H|h)(T|t)|(F|f))(T|t)(P|p)((S|s)?)):(/){2})(www\\.)?([a-zA-Z0-9\\-]+\\.)+[a-zA-Z]{2,6}(\\W(.)*$|$)",
      "severity" : "ERROR"
    }

This could be too restrictive especially in those fields where Company-IDs are requested - since those WEB-Identifiers are not under control of public procurement standards.

**Comment by sbo2718** [comment]
Can you provide an url that doesn't match this pattern?

**Comment by gabrieledall** [comment]
öffentlichevergabe.de (is possible although it is internally forwarded to oeffentlichevergabe.de) - but why restricting allowed letters in writing down the URL someone is used to (and german only allows some extra letters).

**Comment by bertrand-lorentz** [comment]
Thanks for your feedback.

The pattern indeed does currently only accept ASCII characters (a-z...). We will look into improving this.

**Comment by jpmckinney** [comment]
FWIW, a user can write the URL with UTF-8 characters, but the application can convert to ASCII (which is what browsers do anyway https://en.wikipedia.org/wiki/Internationalized_domain_name). e.g. that domain becomes xn--ffentlichevergabe-yzb.de

**Comment by rkottmann** [comment]
> öffentlichevergabe.de (is possible although it is internally forwarded to oeffentlichevergabe.de) - but why restricting allowed letters in writing down the URL someone is used to (and german only allows some extra letters).

I agree that the current regex is too restrictive and matches only a very narrow subset of allowed URLs. Modern web URLs allow for Unicode characters in their register-name (host name of authority) as @jpmckinney pointed out.

1. Hence fast first approach is https://stackoverflow.com/questions/5962871/regular-expression-for-unicode-url

If you do not agree to allow for unicode characters  then you might consider

a) to document the exact kind of URLs you are accepting
b) allow for percent encoding in your regex, because the current one does not allow percent encoding in host name, the but should according to https://datatracker.ietf.org/doc/html/rfc3986#page-21 

https://regex101.com/r/7Tg3lU/1

**Comment by jpmckinney** [comment]
For domains, Punycode is used, not percent-encoding, because the DNS nameserver hierarchy is ASCII-only.

I guess a percent-encoded domain is allowed by the RFC. A browser will transform it to Punycode, however, because a DNS request with percent characters will fail.

Anyhow, the current regex is fine if eForms implementations are expected to properly encode URLs.

**Comment by rkottmann** [comment]
I updated https://regex101.com/r/7Tg3lU/2 to show that the current regex does NOT allow percent encoding with the example of the proper percent encoded `%C3%B6ffentlichevergabe.de` aka `öffentlichevergabe.de`.

I would still suggest that at least for the visualisation part of eForms  the regex allows as user friendly URLs as a browser does when entering `öffentlichevergabe.de`. The validation part of eForms XML might very well be more restrictive and only allow precent encoded URLs.

**Comment by mdewinne** [comment]
We have encountered another case of the URL regex being too restrictive (SDK 1.8): top-level domains containing more than 6 characters (e.g. .brussels, .vlaanderen) are refused.

A quick look on https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains reveals that these kind of domains are no longer uncommon.

**Comment by YvesJo** [comment]
Fixed with SDK 1.9

**Comment by eBrasack** [comment]
Dear TED, what will be the new REGEX Pattern, that you will use to check emails in a less restricted way?
