### ISSUE TITLE
Notice aggregated amounts - amounts in example

### ISSUE THREAD

**Issue by pietropalermoIT** [OP-TED/eForms-SDK#570]
The example provided in the documentation Competition Results - Notice aggregated amounts is misleading since how OverallMaximumFrameworkContractsAmount can be 6.000 euro when GroupFrameworkMaximumValueAmount  is 120.000 for GLO-0001 and 80.000 for GLO-0002? examples should be significant so why  OverallMaximumFrameworkContractsAmount differs from TotalAmount? it is expected that in real world the two figures are identical

**Comment by YvesJo** [comment]
Hi Pietro,
Indeed, the OverallMaximumFrameworkContractsAmount as sum of all the Framework Contract amounts should at least be equal to the sum of the two referenced Group associated values as there may additionally be awarded lots not in these groups having associated Framework Agreements. This will get fixed.
"... why OverallMaximumFrameworkContractsAmount differs from TotalAmount?" these differ because they are different objects. Notice Value (BT-161) is about "The _(actual)_ value of all _(execution)_ contracts awarded in this notice, including options and renewals. Framework Contract aren't _(execution)_ contracts per se but will lead to such contracts (contracts settled under a Framework Agreement), once these subsequent contracts awarded, their values will be integrated to the notice value of the notice they will be announced in.
Please note that this channel is dedicated to technical issues only. Topics related to discussions should be submitted via the discussion channel and non-technical questions sent to the helpdesk: [ted@publications.europa.eu](mailto:ted@publications.europa.eu), also I will close this issue.
Thanks for your understanding,

**Comment by pietropalermoIT** [comment]
Thanks
