### ISSUE TITLE
Field BT-05 24 hour rule

### ISSUE THREAD

**Issue by lillabeatak** [OP-TED/eForms-SDK#618]
Why is there a 24-hour rule associated with field BT-05 (Notice Dispatch Date)?

**Comment by YvesJo** [comment]
Hi,
Please for non-issues, use the discussions channel instead. Also for non-technical questions, please address your inquiries directly to the Helpdesk at [ted@publications.europa.eu](mailto:ted@publications.europa.eu).
I close this non-issue.
KR.

**Comment by AnnaKSZ** [comment]
Hi, 

Why do you think, this problem is not a technical issue?
We have the same problem.

One real case:
If the user submit a notice from the prociurement system to eSender on Saturday (it is a real situation) the eSender cannot forward it on Monday because the Schematron rule is blocked it.

Other real case:
Celex: BT-05: "The date and time when the notice has been sent for publication by the buyer."
All notices are manually checked for lawfullness by the eSender (Official Org). This may take 1-2 days. 
That's why the dynamic Schematron validation block this notice.
Now the eSender needs to update this date, so that this date will not be equal to the date "when the notice has been sent for publication by the buyer."

According to local law, the time of sending by the buyer must be indicated, according to the documents, we thought this is BT-05.

Are we wrong? 
What could you suggest?

**Comment by YvesJo** [comment]
Hi,
The concern expressed here is not about the dysfunction of the SDK, it is about a business decision which defines a timeframe for valid notice submission. For business questions, please share your concern directly with the helpdesk.

**Comment by ferrakaop** [comment]
Hello
This question relates to a business decision - there is nothing technically wrong with the rule in the SDK.
For a short business answer, the Publications Office has 5 calendar days to publish a notice from the moment the buyer sends it for publication. We assume the eSender doesn't take took long to forward it, as otherwise this reduces the period the Publications Office has to publish the notice (which might already include non-working days). We consider that 1 day is enough for eSenders to do what they need to do, as well as allowing for any possible technical disruptions.  Currently, eSentool imposes a 12 hour limit for how "old" a notice can be so the rule for eForms is more generous.
For any further questions, please email the TED helpdesk.

**Comment by lillabeatak** [comment]
Hi,

We understand that, but from our point of view the BT-05: "The date and time when the notice has been sent for publication by the buyer." and BT-803 "The date and time the notice was transmitted electronically by the eSender to the Publications Office of the European Union". Field BT-05 contains the 24 hour rule instead of field BT-803.

**Comment by ferrakaop** [comment]
Hello
BT-803 was added in last year's amendment to the eForms regulation and only allows to see how long it takes an eSender to forward the notice from their user/client/buyer to the Publications Office, which should be kept to a minimum.
The important field is BT-05 as this is the dispatch date from the point of view of the buyer, who should be able to count on a publication in the OJS within no more than 5 days, as defined in the directives. The buyer should have to worry about how long an eSender takes to process their notice. From the Publications Office BT-05 is the legally binding date so the rule is set on this field, not on BT-803.
If, as an eSender, you need some days to check what a buyer sends to you before you send it to TED, then perhaps you need to be clearer with your buyers what constitutes the date of dispatch to TED, as this has many implications in the timing of their procurement procedures. If you are already using eSentool, you can probably keep the same definition of the date you already put in the current TED-XML.

**Comment by AnnaKSZ** [comment]
Thanks for your response
Anna
