### ISSUE TITLE
Differences in repeatability across annex and SDK

### ISSUE THREAD

**Issue by jpmckinney** [OP-TED/eForms-SDK#620]
For example, BT-1252 is repeatable in the annex but BT-1252-Procedure is **not** repeatable (and neither is its parent).

Same for:

* BT-124 (BT-124-Lot, BT-124-Part)
* BT-136 (BT-136-Procedure)
* BT-65 (BT-65-Lot)
* BT-754 (BT-754-Lot)
* BT-556 (BT-556-NoticeResult)
* BT-1501 (BT-1501(n)-Contract)

Is there any documentation of such differences?

I assume the change in repeatability was deliberate. (Or perhaps I'm missing some way in which it is effectively repeatable.) For example, I don't see why the following were repeatable in the annex, so it makes sense for eForms to not follow suit:

* BT-754 (Accessibility): The possible codes are semantically disjoint, so no need to repeat.
* BT-556 (Group Framework Value Lot Identifier): Only need to specify the identifier once.

In the other direction, BT-26 (Classification Type) is **not** repeatable in the annex, but I assume it was made repeatable, so that the additional codes in BT-263 (Additional Classification Codes) could have different types and not all the same type.

**Comment by YvesJo** [comment]
Hi,
Thanks for this information.
The first investigations lead to the following outcome:

**Direct award justification (BT-1252, BT-136)**
Further investigations are needed as this also involves Business aspects including conditional rules.

**Atypical tool (BT-124)**
The decision was driven by the uniqueness of the tool (tool name not repeatable), the definition of the BT ("**The** uniform resource locator (e.g. the web address) which gives unrestricted and full direct access to **these** tools and devices") which refers to a single URL for all the tools (if multiples would exist) and the standard limitations (_cbc:AccessToolsURI_ is not repeatable).

**Subcontracting conditions (BT-65)**
The repeatable aspect of the parent node needs to be updated

**Accessibility (BT-754)**
"BT-754 is not repeatable, as the values in the codelist are mutually exclusive." (cf. https://docs.ted.europa.eu/eforms/latest/schema/procedure-lot-part-information.html#accessibilitySection)

**Group Framework Value (BT-556)**
This is due to the selected design option.
A group is a separate object with its own properties. This object has been introduced to prevent repetitions and ensure consistency. Instead of associating the Group Framework Value to each individual lot it contains, this value is associated to the Group of lots whose composition (i.e. lots it contains) is also covered by BG-330.

**Contract Modification (BT-1501)**
In the annex BT-1501 is only about the notice section (Modification Previous Notice Section Identifier) and this is covered with the field BT-1501(s)-Contract whose parent node is repeatable. The Contract Modification Notice has its own Notice ID, and ID of the previous notice is missing, therefore the non-repeatable field BT-1501(n)-Contract has been added

**Comment by jpmckinney** [comment]
Thank you for the clarifications!

Last question on repeatability: I see that BT-1251-Lot and BT-1251-Part (Previous Planning Part Identifier) are non-repeatable in eForms, but were repeatable in the Annex. I had a discussion about these fields in https://github.com/OP-TED/eForms-SDK/discussions/621, but I'm not clear on the difference in repeatability.

**Comment by YvesJo** [comment]
Hi,
The element identified for BT-1251 is not repeatable in UBL but its parent is, the parent of the field BT-1251-xxx is also the parent of BT-125-xxx; so the difference compared to the annex is that both BT-125 and BT-1251 will need to be repeated together when multiple occurrences of BT-1251 will be needed.

**Comment by jpmckinney** [comment]
Thank you! That answers all my questions.
