### ISSUE TITLE
In release 1.8.1, all the notice-type json files, codelists and fields.json are referring to 1.8.0 instead of 1.8.1

### ISSUE THREAD

**Issue by rgannu** [OP-TED/eForms-SDK#752]
In the release of 1.8.1, all the notice-types/*.json have the sdkVersion and metaDataDatabase.version set to "1.8.0" instead of "1.8.1".
Example [2.json](https://github.com/OP-TED/eForms-SDK/blob/6612ac94e89d90123a33ed1d09ec1faa19823fe2/notice-types/2.json#L3)
[Codelists](https://github.com/OP-TED/eForms-SDK/blob/6612ac94e89d90123a33ed1d09ec1faa19823fe2/codelists/currency_eforms-currency.gc#L9), [fields.json](https://github.com/OP-TED/eForms-SDK/blob/6612ac94e89d90123a33ed1d09ec1faa19823fe2/fields/fields.json#L5) are also referencing to "1.8.0" instead of "1.8.1".

Same problem exists for the release 1.9.1 as well.
Example: [2.json](https://github.com/OP-TED/eForms-SDK/blob/967d5f228881b0c6da6eda9b67e9a1df3e985c2a/notice-types/2.json#L3)

Could you please update it?

**Comment by bertrand-lorentz** [comment]
There were no change in the notice-types/ folder for SDK 1.8.1 or 1.9.1, so the files were left as they were.
We had added the various "sdkVersion" properties in the early days, but since then we've realized that they are redundant and not really useful: it's the version of the SDK as a whole that matters, not what's indicated in each individual file. And mixing files from different versions should be avoided anyways, as they could be inconsistent.

The content of the "metadataDatabase" property is only for us to relate the data in the file to a particular state of our database. So it is not meaningful to consumers of the SDK.

If we had realized this before version 1.0.0, we would probably have removed those properties. But now we have to keep them, as removing them would be technically not backwards compatible.

So when using the SDK, I would recommend to ignore the "sdkVersion" and "metadataDatabase" properties, and only use the SDK version number indicated either in the pom.xml or in the toplevel file "VERSION" (its content is updated automatically when a JAR package is created).

If the above is not an option, could you give more information on why you need to use the version number indicated in the "notice-types/*.json" files ?

**Comment by rgannu** [comment]
We are not using the field value explicitly. For filling in the `OPT-002-notice` we use only the major and minor version as `eforms-sdk-1.8`. 
But, it is confusing when someone see the values in the json files, codelists etc.,

You can mark the ticket as resolved.

**Comment by bertrand-lorentz** [comment]
Thanks for you feedback. We'll try to clarify the description of those properties in the documentation.
