### ISSUE TITLE
BT-78-Lot in wrong Group (Notice Types)

### ISSUE THREAD

**Issue by JulianMa** [OP-TED/eForms-SDK#765]
The Field `BT-78-Lot` (Security Clearance Deadline) is currently inside `GR-Lot-Requirements2SecurityClearance1`, which doesn't make sense.
It should be inside `GR-Lot-SecurityClearance2`. 

It should also be forbidden, when `BT-801-Lot`(Security Clearance) is not set to `true`.

Right now, the selection for the Security Clearance Deadline is above the group with the combobox, in which you select if you even need a clearance.

**Comment by YvesJo** [comment]
Hi Julian,
the rules that control the existence of BT-78-Lot depending on BT-801-Lot (i.e. BR-BT-00078-0012 ...) are defined and inactive since SDK 1.3. They will be reactivated with SDK 1.11 as part of our progressive conditional rules reactivation.
Regarding the Display Group the field has been added to, I will report your observation to the person in charge of the NTDs.
KR.

**Comment by JulianMa** [comment]
Thank you!
