### ISSUE TITLE
Schematrons are not valid against Schematron Grammar

### ISSUE THREAD

**Issue by rkottmann** [OP-TED/eForms-SDK#782]
Hi,

since 1.10.0 where you introduced phases like e.g.

```xml
<phase id="3">
```

The Schematron files are not valid Schematron files anymore.

Reason: anything of type ID or IDREF in XML are NCNames which are not allowed to start with a number.

See 
https://stackoverflow.com/questions/1631396/what-is-an-xsncname-type-and-when-should-it-be-used and https://www.w3.org/TR/xml-names/#NT-NCName

P.S.: Please validate the Schematron files before commiting

**Comment by bertrand-lorentz** [comment]
Thanks for reporting this issue.

We will probably have to add a fixed prefix to all phase identifiers, for example: `<phase id="phase_3">`

We always execute the Schematron files before committing them to check that they work. And for the addition of the phases, I've tested them with several Schematron implementation. But it seems none of those do a full validation against the RELAX NG schema defined in the ISO standard.

Did you detect this when trying to execute the Schematron files, or when opening them with a "Schematron-aware" editor? Which implementation or editor did you use ?

In order to avoid this kind of errors in the future, we plan to add in the [SDK Analyzer](https://github.com/OP-TED/eforms-sdk-analyzer) a check that will do the complete validation against the schema.

**Comment by rkottmann** [comment]
> Did you detect this when trying to execute the Schematron files, or when opening them with a "Schematron-aware" editor?

Yes, we use a commercial "Schematron-aware" XML editor which automatically validates Schematron files.  But we also validate in CI/CD pipelines. 

> In order to avoid this kind of errors in the future, we plan to add in the [SDK Analyzer](https://github.com/OP-TED/eforms-sdk-analyzer) a check that will do the complete validation against the schema.

sounds good :)

**Comment by bertrand-lorentz** [comment]
This will be resolved in the upcoming version 1.11.0: the phase identifiers will all have a prefix "eforms-" (for example "eforms-16").

This change is already available in the "develop" and "prepare/1.11.0" branches.

So I'm closing this.
