### ISSUE TITLE
Missing logic regarding generating attributes in BT-23-Lot

### ISSUE THREAD

**Issue by PiotrRymarz** [OP-TED/eForms-SDK#879]
Hi,
I have question regarding field BT-23-Lot. Comparing it to BT-23-Procedure it is lacking "attributes" field BUT listName attribute is mandatory for both fields.

Similar issue was reported here https://github.com/OP-TED/eForms-SDK/issues/269 but proposed solution is missing vital point in my opinion.

How should we know if a field should contain attribute or not?
for comparison look at BT-97-Lot. It also contains code list node, but as far as i can see it does not require any attribute?

Code list from BT-97
`    "codeList" : {
      "value" : {
        "id" : "eforms-language",
        "type" : "flat",
        "parentId" : "language"
      },
      "severity" : "ERROR"
    }`
 
Simplifying question: How should we know when to create mandatory attributes, when there is no attributes field in field definition?

**Comment by YvesJo** [comment]
Hi,
Thanks for reporting this issue.
The field for the listName attribute of BT-23-Lot is actually missing and this will get fixed with SDK 1.12
With a previous version of the SDK, fields were defined for attributes which weren't already explicitly associated to a field. This initiative was done to remove the ambiguity of some implicit rules. The discussion referred to took place before the definition of these attribute fields.
The XML element that is carrying the BT-97 information is, as defined in the XSD, of type identifier and does therefore not have a listName attribute.
For every mandatory XML element attribute, there should be an associated field defined.
KR

**Comment by PiotrRymarz** [comment]
Thanks for clarification
