### ISSUE TITLE
Observation from our developers: ContractingPartyType/PartyType doesn't exist

### ISSUE THREAD

**Issue by troa1** [OP-TED/eForms-SDK#96]
pin-buyer_24_published.xml
        <cac:ContractingPartyType>
            <cbc:PartyType>IRCSS</cbc:PartyType>
        </cac:ContractingPartyType>

ContractingPartyType/PartyType doesn't exist. 

**Should this be ContractingPartyType/PartyTypeCode instead?**

and

pin-only_24.xml and pin-only_fin-reg.xml
<cac:ProcurementProject>
    <cac:RealizedLocation>
        <cac:Address>
            <cbc:Department>RealizedLocDept1234</cbc:Department>

Department in ProcurementProject.RealizedLocation.Address context doesn't exist in fields.json. 

**Should this be removed?**

**Comment by bertrand-lorentz** [comment]
Thank you for your feedback.

In `pin-buyer_24_published.xml`, this occurrence of `cac:ContractingPartyType` is indeed incorrect and will be removed. There's already a correct `cac:ContractingPartyType` with `cbc:PartyTypeCode`.

There should indeed not be any `cbc:Department` under `cac:RealizedLocation`, so they will be removed from `pin-only_24.xml` and `pin-only_fin-reg.xml`.

For your information, we haven't put in place yet any check that detect "unexpected" XML elements, which is why the notice examples still contain this kind of mistake.

**Comment by bertrand-lorentz** [comment]
The corrections are included in version 1.1.0 that was just released, so I'm closing this.
